### ISSUE TITLE
Clio infrastructure monitoring (Prometheus) showing no data

### ISSUE THREAD

**Issue by PaulMoney** [XRPLF/clio#998]
Hello,

Recently, you have published an ability to set up Prometheus and Grafana dashboards to monitor Clio service health.

I tried 2 different ways testing this feature.

1) I have started the Clio server on one VM, and on another VM, I have cloned the Clio repository and deployed Prometheus and Grafana, following the instructions provided [here](https://github.com/XRPLF/clio/blob/develop/examples/infrastructure/README.md)

I added these lines in my Clio configuration file:

```yaml
"admin_password": "secret",
"local_admin": false
```

Also, I modified prometheus.yml file:

```yaml
scrape_configs:
- job_name: clio
  scrape_interval: 5s
  scrape_timeout: 5s
  authorization:
    type: Password
    credentials: 2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b
  static_configs:
  - targets:
    - <my_clio_public_ip>:51233
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - localhost:9090
```

2) I deployed Prometheus and Grafana on the same VM where Clio is running. 

I modified these lines in my Clio configuration file:

```yaml
"admin_password": "secret"
```

Also, I modified prometheus.yml file:

```yaml
scrape_configs:
- job_name: clio
  scrape_interval: 5s
  scrape_timeout: 5s
  authorization:
    type: Password
    credentials: 2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b
  static_configs:
  - targets:
    - localhost:51233
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - localhost:9090
```

However, in both cases, when I navigated to the Grafana dashboard, I only saw "No data" on every panel.

In both cases, I'm running version 1.0.4 of Clio. Maybe I'm missing something in my configuration, or this feature is not supported on this version of the Clio server?
